- type: job
  id: WarderingTrader
  name: job-name-wardering-trader
  description: job-description-wardering-trader
  playTimeTracker: JobWarderingTrader
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
  weight: 10
  startingGear: WarderingTraderGear
  icon: "JobIconWarderingTrader"
  supervisors: job-supervisors-no-one
  canBeAntag: false
  # access:
  # - Cargo
  # - Salvage
  # - Quartermaster
  # - Maintenance
  # - External
  # - Command
  # - Brig
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
    # implants: [ MindShieldImplant ]
  # - !type:AddComponentSpecial
    # components:
      # - type: CommandStaff
      # - type: PetrTarget

- type: startingGear
  id: WarderingTraderGear
  # equipment:
    # id: QuartermasterPDA
    # ears: ClothingHeadsetQM
    # belt: BoxFolderClipboardThreePapers
    # pocket1: AppraisalTool
  # storage:
    # back:
    # - Flash

- type: playTimeTracker
  id: JobWarderingTrader
