- type: job
  id: Witch
  name: job-name-witch
  description: job-description-witch
  playTimeTracker: JobWitch
  startingGear: WitchGear
  icon: "JobIconWitch"
  supervisors: job-supervisors-no-one
  canBeAntag: false
  # access:
  # - Security
  # - Brig
  # - Maintenance
  # - Service
  # - External
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
    # implants: [ MindShieldImplant ]
  # - !type:AddComponentSpecial
    # components:
      # - type: PetrTarget

- type: startingGear
  id: WitchGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
  storage:
    back:
    - Flash
    - MagazinePistol

- type: playTimeTracker
  id: JobWitch
