- type: job
  id: Peasant
  name: job-name-peasant
  description: job-description-peasant
  playTimeTracker: JobPeasant
  startingGear: PeasantGear
  icon: "JobIconPeasant"
  supervisors: job-supervisors-sheriff
  # access:
  # - Maintenance

- type: startingGear
  id: PeasantGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff
