- type: job
  id: SiegeEngineer
  name: job-name-warrior-siege-engineer
  description: job-description-siege-engineer
  playTimeTracker: JobSiegeEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Warriors
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
  startingGear: SiegeEngineerGear
  icon: "JobIconSiegeEngineer"
  supervisors: job-supervisors-knight
  canBeAntag: false
  # access:
  # - Security
  # - Brig
  # - Maintenance
  # - Service
  # - External
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
    # implants: [ MindShieldImplant ]
  # - !type:AddComponentSpecial
    # components:
      # - type: PetrTarget

- type: startingGear
  id: SiegeEngineerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
  storage:
    back:
    - Flash
    - MagazinePistol

- type: playTimeTracker
  id: JobSiegeEngineer
