using Content.Client.Weapons.Ranged.Systems;
using Content.Shared.Mech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui.Equipment;

[GenerateTypedNameReferences]
public sealed partial class MechGunUiFragment : BoxContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private GunSystem.AmmoStatusControl _bullet;

    public MechGunUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bullet = new GunSystem.AmmoStatusControl()
        {
            MinHeight = 15,
            VerticalAlignment = VAlignment.Center,
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        Container.AddChild(_bullet);
    }

    public void UpdateContents(MechGunUiState state)
    {
        _bullet.Update(state.Count, state.Capacity);
    }
}
