## Static

- type: latheRecipePack
  id: ServiceStatic
  recipes:
  - Bucket
  - Ashtray
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  - FoodPlate
  - FoodPlateSmall
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - FoodBowlBig
  - FoodPlateTin
  - FoodPlateMuffinTin
  - FoodKebabSkewer
  - SprayBottle
  - TrashBag
  - LightReplacer
  - MopItem
  - Holoprojector
  - WetFloorSign
  - WireBrush
  - DrinkVacuumFlask
  - DrinkFlaskBar
  - DrinkShaker
  - DrinkJigger
  - Spoon
  - Fork
  - SpoonPlastic
  - RollingPin
  - ForkPlastic
  - KnifePlastic
  - PairedChopsticks
  - DrinkIceBucket
  - BarSpoon
  - ButchCleaver
  - KitchenKnife
  - Plunger
  - Mousetrap
  - HydroponicsToolSpade
  - BikeHorn
  - ClownRecorder
  - LauncherCreamPie
  - HydroponicsToolScythe
  - HydroponicsToolHatchet

- type: latheRecipePack
  id: ServiceBoardsStatic
  recipes:
  - BiogeneratorMachineCircuitboard
  - UniformPrinterMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - SmartFridgeCircuitboard
  - PrinterDocMachineCircuitboard # Corvax-Printer

- type: latheRecipePack
  id: ServiceEmagStatic
  recipes:
  - CluwneHorn
## Dynamic

- type: latheRecipePack
  id: Janitor
  recipes:
  - AdvMopItem
  - WeaponSprayNozzle
  - ClothingBackpackWaterTank
  - MegaSprayBottle
  - TrashBagBlue
  - BlueSpaceLightReplacer
  - BorgModuleAdvancedCleaning

- type: latheRecipePack
  id: Instruments
  recipes:
  - SynthesizerInstrument
  - PushHorn

- type: latheRecipePack
  id: ServiceBoards
  recipes:
  - BiofabricatorMachineCircuitboard
  - FatExtractorMachineCircuitboard
  - HydroponicsTrayMachineCircuitboard # roundstart gear being unlocked roundstart when
  - SeedExtractorMachineCircuitboard # ^
  - MassMediaCircuitboard
  - ReagentGrinderIndustrialMachineCircuitboard
  - JukeboxCircuitBoard
  - DawInstrumentMachineCircuitboard
