- type: playTimeTracker
  id: JobCargoTeacher

- type: playTimeTracker
  id: JobEngTeacher

- type: playTimeTracker
  id: JobSecTeacher

- type: playTimeTracker
  id: JobSciTeacher

- type: playTimeTracker
  id: JobMedTeacher
