- type: department
  id: Workmans
  name: department-Workmans
  description: department-Workmans-description
  color: "#A46106"
  roles:
  - Workman
  - Kastel

- type: department
  id: Peasants
  name: department-Peasants
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Peasant
  - Sheriff

- type: department
  id: HighNobles
  name: department-High-Nobles
  description: department--High-Nobles-description
  color: "#c41616"
  roles:
  - Messenger
  - KingKnight
  - KingBishop
  - Healer
  editorHidden: true
  weight: 120

- type: department
  id: Nobles
  name: department-Nobles
  description: department-Nobles-description
  color: "#c41616"
  roles:
  - Lord
  - Kastel
  - Bishop
  - Knight
  - Sheriff
  primary: false
  weight: 100

- type: department
  id: Warriors
  name: department-Warriors
  description: department-Warriors-description
  color: "#4457d4"
  weight: 20
  roles:
  - Warrior
  - Squire
  - Sergeant
  - SiegeEngineer
  - Knight

- type: department
  id: Clerical
  name: department-Clerical
  description: department-Science-description
  color: "#a3a3a3"
  roles:
  - Monk
  - Novitius
  - Priest
  - Bishop

- type: department
  id: Outer
  name: department-Outer
  description: department-Outer-description
  color: "#383838"
  weight: 10
  roles:
  - Bandit
  - Witch
  - WarderingTrader
  - WarderingKnight
  - Outcast
